Add retries workflow for Invoke-ScriptAnalyzer
Lombiq/PowerShell-Analyzers pull request #34
Opened 2023-10-25 12:24 UTC by tteguayco

The solution included in this PR implements a maximum of 3 retries per file when they cause an exception at the following statement:

`Invoke-ScriptAnalyzer -Path $PSItem.FullName @analyzerParameters`

2023-10-27 08:44 UTC, DAud-IcI requested changes

2023-10-27 08:44 UTC, DAud-IcI commented on Lombiq.Analyzers.PowerShell/Invoke-Analyzer.ps1
> +        while ($retryCount -lt $maxRetries)
Since you don't use the `$retryCount` outside of this loop, you could make this a `for` instead.

2023-10-27 08:44 UTC, DAud-IcI commented on Lombiq.Analyzers.PowerShell/Invoke-Analyzer.ps1
> +                Invoke-ScriptAnalyzer -Path $PSItem.FullName @analyzerParameters
I think it would be valuable to enable the `-Verbose` flag on second and third attempts, but not on the first attempt.

2023-10-29 12:25 UTC, DAud-IcI approved these changes

2023-10-29 19:02 UTC, DemeSzabolcs approved these changes

2023-10-29 19:03 UTC, merged